artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  taxi_data_url: https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page
  weather_data_url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
  taxi_data_local_file_path: artifacts/data_ingestion/taxi_data.parquet
  weather_data_local_file_path: artifacts/data_ingestion/weather_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  feature_store_url_path: ssd
  shapfile_dir: artifacts/data_transformation/shapefile
  taxi_zone_shapefile_url: https://d37ci6vzurychx.cloudfront.net/misc/taxi_zones.zip
  transformed_data_file_path: artifacts/data_transformation/transformed_data.parquet


model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/model_training/train.csv
  val_data_path: artifacts/model_training/val.csv
  test_data_path: artifacts/model_training/test.csv
  trained_model_path: artifacts/model_training/model/model.pkl

inference:
  root_dir: artifacts/inference
  input_data_path: artifacts/inference/input_data.csv
  model_path: artifacts/inference/model.pkl
  predictions_output_path: artifacts/inference/predictions.json
  zone_lookup_url : "https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv"
  shapfile_dir: artifacts/inference/shapefile
  geojson_output_path: artifacts/inference/NYC_Taxi_Zones.geojson
  taxi_zone_shapefile_url: https://d37ci6vzurychx.cloudfront.net/misc/taxi_zones.zip
  
  
  