name: Keep Render Alive

on:
  # This replaces the 'schedule' section
  workflow_dispatch:
    types: [easycron_job]

permissions:
  contents: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render URL
        run: curl -s https://nyc-ride-demand.onrender.com/ > /dev/null